### ISSUE TITLE
Unknown cipher

### ISSUE THREAD

**Issue by Silbad** [kunalpanchal/secure-env#2]
Hug,
I recently updated my package.json with Yarn and I have this issue on start
`
Secure-env :  ERROR OCCURED Error: Unknown cipher`
An idea ?

**Comment by kunalpanchal** [comment]
May I know your node version?

**Comment by Silbad** [comment]
yarn versions v1.13.0
{ yarn: '1.13.0',
  StackBook: '1.0.0',
  http_parser: '2.8.0',
  node: '8.11.1',
  v8: '6.2.414.50',
  uv: '1.19.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2o',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }

**Comment by Silbad** [comment]
ok, I've updated node to '11.6.0', same issue...

**Comment by Silbad** [comment]
+ infos, I use it with electron.js
I see this issue : https://github.com/electron/electron/pull/16617
But the version 4.0.4 don't fix this issue... :(

**Comment by kunalpanchal** [comment]
Fixed with #10
